# Generated by Django 5.2.4 on 2025-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0005_product_available_sizes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(
                blank=True, help_text="Selected size (e.g., S, M, L)", max_length=30
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "size")},
        ),
    ]
