# Generated by Django 5.2.4 on 2025-11-12 01:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_wishlistitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("user", "product")},
        ),
    ]
