# Generated by Django 5.2.4 on 2025-11-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_wishlistitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
