# Generated by Django 5.2.4 on 2025-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_delete_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated sizes like XS,S,M,L,XL",
                max_length=255,
            ),
        ),
    ]
