# Generated by Django 5.2.8 on 2025-11-16 07:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, help_text='Unique payment transaction ID', max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20)),
                ('payment_gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('manual', 'Manual')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full response from payment gateway', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure if any', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was successfully completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_id'], name='orders_paym_payment_7cce51_idx'), models.Index(fields=['order', '-created_at'], name='orders_paym_order_i_ee6c4b_idx'), models.Index(fields=['status'], name='orders_paym_status_83f434_idx'), models.Index(fields=['razorpay_order_id'], name='orders_paym_razorpa_9a8915_idx')],
            },
        ),
    ]
