# Generated by Django 5.2.4 on 2025-11-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_shippingaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
