# Generated by Django 5.2.4 on 2025-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_delete_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                blank=True, help_text="Selected size for this item", max_length=30
            ),
        ),
    ]
